//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/TDCB/Scripts/Runtime/Input/InputControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputControls"",
    ""maps"": [
        {
            ""name"": ""PlayerInput"",
            ""id"": ""4dafb3d7-a66b-41b1-8ebd-9a94b35aa343"",
            ""actions"": [
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""add35f73-fee1-4566-b9c2-34fe5fb11ae7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""27bb6c13-d642-4eec-947e-df2dc6da2d33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseDelta"",
                    ""type"": ""Value"",
                    ""id"": ""5e8d8ef9-431f-4a6e-8a42-e61ab4d526cf"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftMousePress"",
                    ""type"": ""Button"",
                    ""id"": ""6c80d2cf-5b30-4730-8bec-03751f3d0ce8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftMouseRelease"",
                    ""type"": ""Button"",
                    ""id"": ""c4922d3c-0aa6-4a48-96db-5b793b60bc73"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightMousePress"",
                    ""type"": ""Button"",
                    ""id"": ""a5072a0e-c083-4bfe-b277-00ef3c734e78"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightMouseRelease"",
                    ""type"": ""Button"",
                    ""id"": ""ee8be2ab-d936-4599-9878-79d88ceb510f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollDelta"",
                    ""type"": ""Value"",
                    ""id"": ""6a8a02e1-96df-4390-a219-23302f95fb3e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""98bccb29-715a-4348-8f2b-e7b04891b8cb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PanCamera"",
                    ""type"": ""Value"",
                    ""id"": ""e704c9e9-cfb0-41fa-b673-728f306c2597"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4930124b-d3d2-4fec-af2f-9c28fc754914"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e0c66f6-0c44-4b40-a27c-6e977c0271c4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d61d91a-ee34-423f-88ca-b7b05b99fe6a"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76713f84-62b8-482a-80e1-1b744b32142c"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightMousePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6f9c706-8508-4c72-8dfe-ba156db1fbab"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightMouseRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e32e95cf-cb6c-4786-ae90-9e1544d59a2b"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""566dffb9-e583-4f7f-8afe-aef32f77adb4"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80fbc17b-3a6e-4f2e-9a40-7f0a72bbf067"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftMousePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bb819a2-0244-4701-89ef-b60d50053dee"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftMouseRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d26dfc4-fc98-4885-bdcb-81f3867d2fc4"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PanCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62b7666c-d0ff-4a6a-a958-9ffaa3cfa17d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PanCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInput
        m_PlayerInput = asset.FindActionMap("PlayerInput", throwIfNotFound: true);
        m_PlayerInput_Select = m_PlayerInput.FindAction("Select", throwIfNotFound: true);
        m_PlayerInput_Cancel = m_PlayerInput.FindAction("Cancel", throwIfNotFound: true);
        m_PlayerInput_MouseDelta = m_PlayerInput.FindAction("MouseDelta", throwIfNotFound: true);
        m_PlayerInput_LeftMousePress = m_PlayerInput.FindAction("LeftMousePress", throwIfNotFound: true);
        m_PlayerInput_LeftMouseRelease = m_PlayerInput.FindAction("LeftMouseRelease", throwIfNotFound: true);
        m_PlayerInput_RightMousePress = m_PlayerInput.FindAction("RightMousePress", throwIfNotFound: true);
        m_PlayerInput_RightMouseRelease = m_PlayerInput.FindAction("RightMouseRelease", throwIfNotFound: true);
        m_PlayerInput_ScrollDelta = m_PlayerInput.FindAction("ScrollDelta", throwIfNotFound: true);
        m_PlayerInput_MousePosition = m_PlayerInput.FindAction("MousePosition", throwIfNotFound: true);
        m_PlayerInput_PanCamera = m_PlayerInput.FindAction("PanCamera", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInput
    private readonly InputActionMap m_PlayerInput;
    private List<IPlayerInputActions> m_PlayerInputActionsCallbackInterfaces = new List<IPlayerInputActions>();
    private readonly InputAction m_PlayerInput_Select;
    private readonly InputAction m_PlayerInput_Cancel;
    private readonly InputAction m_PlayerInput_MouseDelta;
    private readonly InputAction m_PlayerInput_LeftMousePress;
    private readonly InputAction m_PlayerInput_LeftMouseRelease;
    private readonly InputAction m_PlayerInput_RightMousePress;
    private readonly InputAction m_PlayerInput_RightMouseRelease;
    private readonly InputAction m_PlayerInput_ScrollDelta;
    private readonly InputAction m_PlayerInput_MousePosition;
    private readonly InputAction m_PlayerInput_PanCamera;
    public struct PlayerInputActions
    {
        private @InputControls m_Wrapper;
        public PlayerInputActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Select => m_Wrapper.m_PlayerInput_Select;
        public InputAction @Cancel => m_Wrapper.m_PlayerInput_Cancel;
        public InputAction @MouseDelta => m_Wrapper.m_PlayerInput_MouseDelta;
        public InputAction @LeftMousePress => m_Wrapper.m_PlayerInput_LeftMousePress;
        public InputAction @LeftMouseRelease => m_Wrapper.m_PlayerInput_LeftMouseRelease;
        public InputAction @RightMousePress => m_Wrapper.m_PlayerInput_RightMousePress;
        public InputAction @RightMouseRelease => m_Wrapper.m_PlayerInput_RightMouseRelease;
        public InputAction @ScrollDelta => m_Wrapper.m_PlayerInput_ScrollDelta;
        public InputAction @MousePosition => m_Wrapper.m_PlayerInput_MousePosition;
        public InputAction @PanCamera => m_Wrapper.m_PlayerInput_PanCamera;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerInputActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Add(instance);
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @MouseDelta.started += instance.OnMouseDelta;
            @MouseDelta.performed += instance.OnMouseDelta;
            @MouseDelta.canceled += instance.OnMouseDelta;
            @LeftMousePress.started += instance.OnLeftMousePress;
            @LeftMousePress.performed += instance.OnLeftMousePress;
            @LeftMousePress.canceled += instance.OnLeftMousePress;
            @LeftMouseRelease.started += instance.OnLeftMouseRelease;
            @LeftMouseRelease.performed += instance.OnLeftMouseRelease;
            @LeftMouseRelease.canceled += instance.OnLeftMouseRelease;
            @RightMousePress.started += instance.OnRightMousePress;
            @RightMousePress.performed += instance.OnRightMousePress;
            @RightMousePress.canceled += instance.OnRightMousePress;
            @RightMouseRelease.started += instance.OnRightMouseRelease;
            @RightMouseRelease.performed += instance.OnRightMouseRelease;
            @RightMouseRelease.canceled += instance.OnRightMouseRelease;
            @ScrollDelta.started += instance.OnScrollDelta;
            @ScrollDelta.performed += instance.OnScrollDelta;
            @ScrollDelta.canceled += instance.OnScrollDelta;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
            @PanCamera.started += instance.OnPanCamera;
            @PanCamera.performed += instance.OnPanCamera;
            @PanCamera.canceled += instance.OnPanCamera;
        }

        private void UnregisterCallbacks(IPlayerInputActions instance)
        {
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @MouseDelta.started -= instance.OnMouseDelta;
            @MouseDelta.performed -= instance.OnMouseDelta;
            @MouseDelta.canceled -= instance.OnMouseDelta;
            @LeftMousePress.started -= instance.OnLeftMousePress;
            @LeftMousePress.performed -= instance.OnLeftMousePress;
            @LeftMousePress.canceled -= instance.OnLeftMousePress;
            @LeftMouseRelease.started -= instance.OnLeftMouseRelease;
            @LeftMouseRelease.performed -= instance.OnLeftMouseRelease;
            @LeftMouseRelease.canceled -= instance.OnLeftMouseRelease;
            @RightMousePress.started -= instance.OnRightMousePress;
            @RightMousePress.performed -= instance.OnRightMousePress;
            @RightMousePress.canceled -= instance.OnRightMousePress;
            @RightMouseRelease.started -= instance.OnRightMouseRelease;
            @RightMouseRelease.performed -= instance.OnRightMouseRelease;
            @RightMouseRelease.canceled -= instance.OnRightMouseRelease;
            @ScrollDelta.started -= instance.OnScrollDelta;
            @ScrollDelta.performed -= instance.OnScrollDelta;
            @ScrollDelta.canceled -= instance.OnScrollDelta;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
            @PanCamera.started -= instance.OnPanCamera;
            @PanCamera.performed -= instance.OnPanCamera;
            @PanCamera.canceled -= instance.OnPanCamera;
        }

        public void RemoveCallbacks(IPlayerInputActions instance)
        {
            if (m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerInputActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerInputActions @PlayerInput => new PlayerInputActions(this);
    public interface IPlayerInputActions
    {
        void OnSelect(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnMouseDelta(InputAction.CallbackContext context);
        void OnLeftMousePress(InputAction.CallbackContext context);
        void OnLeftMouseRelease(InputAction.CallbackContext context);
        void OnRightMousePress(InputAction.CallbackContext context);
        void OnRightMouseRelease(InputAction.CallbackContext context);
        void OnScrollDelta(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnPanCamera(InputAction.CallbackContext context);
    }
}
