//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/TDCB/Scripts/Runtime/Input/InputControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputControls"",
    ""maps"": [
        {
            ""name"": ""PlayerInput"",
            ""id"": ""4dafb3d7-a66b-41b1-8ebd-9a94b35aa343"",
            ""actions"": [
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""add35f73-fee1-4566-b9c2-34fe5fb11ae7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""27bb6c13-d642-4eec-947e-df2dc6da2d33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseDelta"",
                    ""type"": ""Value"",
                    ""id"": ""5e8d8ef9-431f-4a6e-8a42-e61ab4d526cf"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftMousePress"",
                    ""type"": ""Button"",
                    ""id"": ""6c80d2cf-5b30-4730-8bec-03751f3d0ce8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftMouseRelease"",
                    ""type"": ""Button"",
                    ""id"": ""c4922d3c-0aa6-4a48-96db-5b793b60bc73"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightMousePress"",
                    ""type"": ""Button"",
                    ""id"": ""a5072a0e-c083-4bfe-b277-00ef3c734e78"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightMouseRelease"",
                    ""type"": ""Button"",
                    ""id"": ""ee8be2ab-d936-4599-9878-79d88ceb510f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollDelta"",
                    ""type"": ""Value"",
                    ""id"": ""6a8a02e1-96df-4390-a219-23302f95fb3e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""98bccb29-715a-4348-8f2b-e7b04891b8cb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Control"",
                    ""type"": ""Button"",
                    ""id"": ""0ad3fdf5-d8cd-4bf9-93d8-865a264a08da"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4930124b-d3d2-4fec-af2f-9c28fc754914"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e0c66f6-0c44-4b40-a27c-6e977c0271c4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9c9b5c7-b2ea-429f-b1a1-8e843c4ce413"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d61d91a-ee34-423f-88ca-b7b05b99fe6a"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76713f84-62b8-482a-80e1-1b744b32142c"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightMousePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6f9c706-8508-4c72-8dfe-ba156db1fbab"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightMouseRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e32e95cf-cb6c-4786-ae90-9e1544d59a2b"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""566dffb9-e583-4f7f-8afe-aef32f77adb4"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80fbc17b-3a6e-4f2e-9a40-7f0a72bbf067"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftMousePress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bb819a2-0244-4701-89ef-b60d50053dee"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftMouseRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3fc0fdda-75a3-496e-b331-b9538f1dff63"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Control"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CameraControls"",
            ""id"": ""bbb44198-0280-446a-b71e-fcd73ae78b1b"",
            ""actions"": [
                {
                    ""name"": ""CameraMovement"",
                    ""type"": ""Value"",
                    ""id"": ""55bb9e46-6f6f-4a9f-b995-154416806628"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraSpeedModifier"",
                    ""type"": ""Button"",
                    ""id"": ""b8f55d92-1706-41bb-8685-a3ed1f4c1972"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraZoom"",
                    ""type"": ""Value"",
                    ""id"": ""ffdd58f8-8614-4cda-aba5-11b19e5f18cf"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateCamera"",
                    ""type"": ""Button"",
                    ""id"": ""3d646eab-3673-4ced-817b-10bf29565f98"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PanCamera"",
                    ""type"": ""Value"",
                    ""id"": ""1bf47f03-4cbf-45da-946e-5e599130244c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FocusCamera"",
                    ""type"": ""Button"",
                    ""id"": ""0af7f777-d016-4fa5-9b54-3a7107926dd7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""d9c3e2fd-b1ab-42e1-9cb6-5a97dfc05c64"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bb60bd7b-7243-4cdb-a0f4-5a87ab9c88ac"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bc055617-c28e-4d31-92f6-249d7ced5234"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9422314b-6675-45c7-b727-d0248740cac2"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f67113bb-b9a8-4115-9f2e-8c1a26818f0a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c592de88-da1a-4d69-b216-62a1fa2d90a5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""61ed395c-97f3-49d5-a90e-038de1e7832b"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8dc4b593-abd4-41bc-bf4a-a32b6568a4a1"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""14fc4a2b-7d41-4aa1-ac99-ae0d4d4b21c0"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bc818f48-c849-45cf-a837-000c3dcef518"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""e689a615-5c18-4498-8726-c1d2819258c0"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7b5bfa80-0685-4cfb-b078-5f02a9f38a1d"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""57be0ffe-a912-4077-a3cd-da4e7ae7935f"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c66e5efe-44a2-4590-ada3-89df4022191e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e97c4a58-dfe0-4296-8518-9b82852d33d0"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PanCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6314f28e-b55b-4123-9844-30a30cf84506"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraSpeedModifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a64d489-1bb8-4e14-8cda-deebb7f9edee"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FocusCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Commands"",
            ""id"": ""28aa9fab-48a3-4e2d-be1b-0e77cab2b24e"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""fbefda9c-5ac1-4cc6-8c8b-d6848e8f921f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stop"",
                    ""type"": ""Button"",
                    ""id"": ""7cf047e6-d08f-4636-9bb2-0fdec85bee6f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e2b69d47-f5b7-4745-9994-c2a175b843eb"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bcb00b26-2041-46ac-b034-9d173ba10245"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ControlGroups"",
            ""id"": ""2f56ebdf-1fbd-49c4-ada7-df26f359d21b"",
            ""actions"": [
                {
                    ""name"": ""ControlGroup1"",
                    ""type"": ""Button"",
                    ""id"": ""9590fd2d-4ed3-48c2-ba4d-bbe318743d4e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ControlGroup2"",
                    ""type"": ""Button"",
                    ""id"": ""a2c9a1a9-ff5e-4ac7-af08-42e91fa0d8d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ControlGroup3"",
                    ""type"": ""Button"",
                    ""id"": ""5eefc81b-2abe-4b8b-9a7b-f0bea0e914ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ControlGroup4"",
                    ""type"": ""Button"",
                    ""id"": ""f0451449-1a2c-4743-b2b0-c5f3e2093294"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ControlGroup5"",
                    ""type"": ""Button"",
                    ""id"": ""ad8b2fed-4092-416e-9ec3-7cf414423064"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ControlGroup6"",
                    ""type"": ""Button"",
                    ""id"": ""0563e3a7-610a-400f-9b42-a55380264a50"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ControlGroup7"",
                    ""type"": ""Button"",
                    ""id"": ""c41fefe6-3bec-4818-95f7-1e1b1229e96d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ControlGroup8"",
                    ""type"": ""Button"",
                    ""id"": ""c34251b0-0cb3-4073-8ba2-9859b88cccec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ControlGroup9"",
                    ""type"": ""Button"",
                    ""id"": ""2319f6d4-af71-4cc7-94ab-2c9497b1b2f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""99994b39-e1a3-49ba-96fe-41e85309b0e1"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControlGroup1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b408aee9-68b6-4957-ab5b-813ef58a001a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControlGroup2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1726772-f915-487e-86be-b746737b5739"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControlGroup3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1cefc9b4-3745-4e97-ade4-e1f2ba23f1c8"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControlGroup4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7af9861d-2513-4e32-ac51-321ba28822b4"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControlGroup5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d359bfc-bfaf-4a68-9bde-52432c9d6443"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControlGroup6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d70ba23-a29b-4d3a-9d86-ec36486b2495"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControlGroup7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4a43493-0d8b-43a6-88b6-7ada51d46847"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControlGroup8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f01cc774-5ecf-4d4d-bfa5-24aaab8254fd"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ControlGroup9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInput
        m_PlayerInput = asset.FindActionMap("PlayerInput", throwIfNotFound: true);
        m_PlayerInput_Select = m_PlayerInput.FindAction("Select", throwIfNotFound: true);
        m_PlayerInput_Cancel = m_PlayerInput.FindAction("Cancel", throwIfNotFound: true);
        m_PlayerInput_MouseDelta = m_PlayerInput.FindAction("MouseDelta", throwIfNotFound: true);
        m_PlayerInput_LeftMousePress = m_PlayerInput.FindAction("LeftMousePress", throwIfNotFound: true);
        m_PlayerInput_LeftMouseRelease = m_PlayerInput.FindAction("LeftMouseRelease", throwIfNotFound: true);
        m_PlayerInput_RightMousePress = m_PlayerInput.FindAction("RightMousePress", throwIfNotFound: true);
        m_PlayerInput_RightMouseRelease = m_PlayerInput.FindAction("RightMouseRelease", throwIfNotFound: true);
        m_PlayerInput_ScrollDelta = m_PlayerInput.FindAction("ScrollDelta", throwIfNotFound: true);
        m_PlayerInput_MousePosition = m_PlayerInput.FindAction("MousePosition", throwIfNotFound: true);
        m_PlayerInput_Control = m_PlayerInput.FindAction("Control", throwIfNotFound: true);
        // CameraControls
        m_CameraControls = asset.FindActionMap("CameraControls", throwIfNotFound: true);
        m_CameraControls_CameraMovement = m_CameraControls.FindAction("CameraMovement", throwIfNotFound: true);
        m_CameraControls_CameraSpeedModifier = m_CameraControls.FindAction("CameraSpeedModifier", throwIfNotFound: true);
        m_CameraControls_CameraZoom = m_CameraControls.FindAction("CameraZoom", throwIfNotFound: true);
        m_CameraControls_RotateCamera = m_CameraControls.FindAction("RotateCamera", throwIfNotFound: true);
        m_CameraControls_PanCamera = m_CameraControls.FindAction("PanCamera", throwIfNotFound: true);
        m_CameraControls_FocusCamera = m_CameraControls.FindAction("FocusCamera", throwIfNotFound: true);
        // Commands
        m_Commands = asset.FindActionMap("Commands", throwIfNotFound: true);
        m_Commands_Move = m_Commands.FindAction("Move", throwIfNotFound: true);
        m_Commands_Stop = m_Commands.FindAction("Stop", throwIfNotFound: true);
        // ControlGroups
        m_ControlGroups = asset.FindActionMap("ControlGroups", throwIfNotFound: true);
        m_ControlGroups_ControlGroup1 = m_ControlGroups.FindAction("ControlGroup1", throwIfNotFound: true);
        m_ControlGroups_ControlGroup2 = m_ControlGroups.FindAction("ControlGroup2", throwIfNotFound: true);
        m_ControlGroups_ControlGroup3 = m_ControlGroups.FindAction("ControlGroup3", throwIfNotFound: true);
        m_ControlGroups_ControlGroup4 = m_ControlGroups.FindAction("ControlGroup4", throwIfNotFound: true);
        m_ControlGroups_ControlGroup5 = m_ControlGroups.FindAction("ControlGroup5", throwIfNotFound: true);
        m_ControlGroups_ControlGroup6 = m_ControlGroups.FindAction("ControlGroup6", throwIfNotFound: true);
        m_ControlGroups_ControlGroup7 = m_ControlGroups.FindAction("ControlGroup7", throwIfNotFound: true);
        m_ControlGroups_ControlGroup8 = m_ControlGroups.FindAction("ControlGroup8", throwIfNotFound: true);
        m_ControlGroups_ControlGroup9 = m_ControlGroups.FindAction("ControlGroup9", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInput
    private readonly InputActionMap m_PlayerInput;
    private List<IPlayerInputActions> m_PlayerInputActionsCallbackInterfaces = new List<IPlayerInputActions>();
    private readonly InputAction m_PlayerInput_Select;
    private readonly InputAction m_PlayerInput_Cancel;
    private readonly InputAction m_PlayerInput_MouseDelta;
    private readonly InputAction m_PlayerInput_LeftMousePress;
    private readonly InputAction m_PlayerInput_LeftMouseRelease;
    private readonly InputAction m_PlayerInput_RightMousePress;
    private readonly InputAction m_PlayerInput_RightMouseRelease;
    private readonly InputAction m_PlayerInput_ScrollDelta;
    private readonly InputAction m_PlayerInput_MousePosition;
    private readonly InputAction m_PlayerInput_Control;
    public struct PlayerInputActions
    {
        private @InputControls m_Wrapper;
        public PlayerInputActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Select => m_Wrapper.m_PlayerInput_Select;
        public InputAction @Cancel => m_Wrapper.m_PlayerInput_Cancel;
        public InputAction @MouseDelta => m_Wrapper.m_PlayerInput_MouseDelta;
        public InputAction @LeftMousePress => m_Wrapper.m_PlayerInput_LeftMousePress;
        public InputAction @LeftMouseRelease => m_Wrapper.m_PlayerInput_LeftMouseRelease;
        public InputAction @RightMousePress => m_Wrapper.m_PlayerInput_RightMousePress;
        public InputAction @RightMouseRelease => m_Wrapper.m_PlayerInput_RightMouseRelease;
        public InputAction @ScrollDelta => m_Wrapper.m_PlayerInput_ScrollDelta;
        public InputAction @MousePosition => m_Wrapper.m_PlayerInput_MousePosition;
        public InputAction @Control => m_Wrapper.m_PlayerInput_Control;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerInputActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Add(instance);
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @MouseDelta.started += instance.OnMouseDelta;
            @MouseDelta.performed += instance.OnMouseDelta;
            @MouseDelta.canceled += instance.OnMouseDelta;
            @LeftMousePress.started += instance.OnLeftMousePress;
            @LeftMousePress.performed += instance.OnLeftMousePress;
            @LeftMousePress.canceled += instance.OnLeftMousePress;
            @LeftMouseRelease.started += instance.OnLeftMouseRelease;
            @LeftMouseRelease.performed += instance.OnLeftMouseRelease;
            @LeftMouseRelease.canceled += instance.OnLeftMouseRelease;
            @RightMousePress.started += instance.OnRightMousePress;
            @RightMousePress.performed += instance.OnRightMousePress;
            @RightMousePress.canceled += instance.OnRightMousePress;
            @RightMouseRelease.started += instance.OnRightMouseRelease;
            @RightMouseRelease.performed += instance.OnRightMouseRelease;
            @RightMouseRelease.canceled += instance.OnRightMouseRelease;
            @ScrollDelta.started += instance.OnScrollDelta;
            @ScrollDelta.performed += instance.OnScrollDelta;
            @ScrollDelta.canceled += instance.OnScrollDelta;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
            @Control.started += instance.OnControl;
            @Control.performed += instance.OnControl;
            @Control.canceled += instance.OnControl;
        }

        private void UnregisterCallbacks(IPlayerInputActions instance)
        {
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @MouseDelta.started -= instance.OnMouseDelta;
            @MouseDelta.performed -= instance.OnMouseDelta;
            @MouseDelta.canceled -= instance.OnMouseDelta;
            @LeftMousePress.started -= instance.OnLeftMousePress;
            @LeftMousePress.performed -= instance.OnLeftMousePress;
            @LeftMousePress.canceled -= instance.OnLeftMousePress;
            @LeftMouseRelease.started -= instance.OnLeftMouseRelease;
            @LeftMouseRelease.performed -= instance.OnLeftMouseRelease;
            @LeftMouseRelease.canceled -= instance.OnLeftMouseRelease;
            @RightMousePress.started -= instance.OnRightMousePress;
            @RightMousePress.performed -= instance.OnRightMousePress;
            @RightMousePress.canceled -= instance.OnRightMousePress;
            @RightMouseRelease.started -= instance.OnRightMouseRelease;
            @RightMouseRelease.performed -= instance.OnRightMouseRelease;
            @RightMouseRelease.canceled -= instance.OnRightMouseRelease;
            @ScrollDelta.started -= instance.OnScrollDelta;
            @ScrollDelta.performed -= instance.OnScrollDelta;
            @ScrollDelta.canceled -= instance.OnScrollDelta;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
            @Control.started -= instance.OnControl;
            @Control.performed -= instance.OnControl;
            @Control.canceled -= instance.OnControl;
        }

        public void RemoveCallbacks(IPlayerInputActions instance)
        {
            if (m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerInputActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerInputActions @PlayerInput => new PlayerInputActions(this);

    // CameraControls
    private readonly InputActionMap m_CameraControls;
    private List<ICameraControlsActions> m_CameraControlsActionsCallbackInterfaces = new List<ICameraControlsActions>();
    private readonly InputAction m_CameraControls_CameraMovement;
    private readonly InputAction m_CameraControls_CameraSpeedModifier;
    private readonly InputAction m_CameraControls_CameraZoom;
    private readonly InputAction m_CameraControls_RotateCamera;
    private readonly InputAction m_CameraControls_PanCamera;
    private readonly InputAction m_CameraControls_FocusCamera;
    public struct CameraControlsActions
    {
        private @InputControls m_Wrapper;
        public CameraControlsActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @CameraMovement => m_Wrapper.m_CameraControls_CameraMovement;
        public InputAction @CameraSpeedModifier => m_Wrapper.m_CameraControls_CameraSpeedModifier;
        public InputAction @CameraZoom => m_Wrapper.m_CameraControls_CameraZoom;
        public InputAction @RotateCamera => m_Wrapper.m_CameraControls_RotateCamera;
        public InputAction @PanCamera => m_Wrapper.m_CameraControls_PanCamera;
        public InputAction @FocusCamera => m_Wrapper.m_CameraControls_FocusCamera;
        public InputActionMap Get() { return m_Wrapper.m_CameraControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraControlsActions set) { return set.Get(); }
        public void AddCallbacks(ICameraControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraControlsActionsCallbackInterfaces.Add(instance);
            @CameraMovement.started += instance.OnCameraMovement;
            @CameraMovement.performed += instance.OnCameraMovement;
            @CameraMovement.canceled += instance.OnCameraMovement;
            @CameraSpeedModifier.started += instance.OnCameraSpeedModifier;
            @CameraSpeedModifier.performed += instance.OnCameraSpeedModifier;
            @CameraSpeedModifier.canceled += instance.OnCameraSpeedModifier;
            @CameraZoom.started += instance.OnCameraZoom;
            @CameraZoom.performed += instance.OnCameraZoom;
            @CameraZoom.canceled += instance.OnCameraZoom;
            @RotateCamera.started += instance.OnRotateCamera;
            @RotateCamera.performed += instance.OnRotateCamera;
            @RotateCamera.canceled += instance.OnRotateCamera;
            @PanCamera.started += instance.OnPanCamera;
            @PanCamera.performed += instance.OnPanCamera;
            @PanCamera.canceled += instance.OnPanCamera;
            @FocusCamera.started += instance.OnFocusCamera;
            @FocusCamera.performed += instance.OnFocusCamera;
            @FocusCamera.canceled += instance.OnFocusCamera;
        }

        private void UnregisterCallbacks(ICameraControlsActions instance)
        {
            @CameraMovement.started -= instance.OnCameraMovement;
            @CameraMovement.performed -= instance.OnCameraMovement;
            @CameraMovement.canceled -= instance.OnCameraMovement;
            @CameraSpeedModifier.started -= instance.OnCameraSpeedModifier;
            @CameraSpeedModifier.performed -= instance.OnCameraSpeedModifier;
            @CameraSpeedModifier.canceled -= instance.OnCameraSpeedModifier;
            @CameraZoom.started -= instance.OnCameraZoom;
            @CameraZoom.performed -= instance.OnCameraZoom;
            @CameraZoom.canceled -= instance.OnCameraZoom;
            @RotateCamera.started -= instance.OnRotateCamera;
            @RotateCamera.performed -= instance.OnRotateCamera;
            @RotateCamera.canceled -= instance.OnRotateCamera;
            @PanCamera.started -= instance.OnPanCamera;
            @PanCamera.performed -= instance.OnPanCamera;
            @PanCamera.canceled -= instance.OnPanCamera;
            @FocusCamera.started -= instance.OnFocusCamera;
            @FocusCamera.performed -= instance.OnFocusCamera;
            @FocusCamera.canceled -= instance.OnFocusCamera;
        }

        public void RemoveCallbacks(ICameraControlsActions instance)
        {
            if (m_Wrapper.m_CameraControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICameraControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CameraControlsActions @CameraControls => new CameraControlsActions(this);

    // Commands
    private readonly InputActionMap m_Commands;
    private List<ICommandsActions> m_CommandsActionsCallbackInterfaces = new List<ICommandsActions>();
    private readonly InputAction m_Commands_Move;
    private readonly InputAction m_Commands_Stop;
    public struct CommandsActions
    {
        private @InputControls m_Wrapper;
        public CommandsActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Commands_Move;
        public InputAction @Stop => m_Wrapper.m_Commands_Stop;
        public InputActionMap Get() { return m_Wrapper.m_Commands; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CommandsActions set) { return set.Get(); }
        public void AddCallbacks(ICommandsActions instance)
        {
            if (instance == null || m_Wrapper.m_CommandsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CommandsActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Stop.started += instance.OnStop;
            @Stop.performed += instance.OnStop;
            @Stop.canceled += instance.OnStop;
        }

        private void UnregisterCallbacks(ICommandsActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Stop.started -= instance.OnStop;
            @Stop.performed -= instance.OnStop;
            @Stop.canceled -= instance.OnStop;
        }

        public void RemoveCallbacks(ICommandsActions instance)
        {
            if (m_Wrapper.m_CommandsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICommandsActions instance)
        {
            foreach (var item in m_Wrapper.m_CommandsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CommandsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CommandsActions @Commands => new CommandsActions(this);

    // ControlGroups
    private readonly InputActionMap m_ControlGroups;
    private List<IControlGroupsActions> m_ControlGroupsActionsCallbackInterfaces = new List<IControlGroupsActions>();
    private readonly InputAction m_ControlGroups_ControlGroup1;
    private readonly InputAction m_ControlGroups_ControlGroup2;
    private readonly InputAction m_ControlGroups_ControlGroup3;
    private readonly InputAction m_ControlGroups_ControlGroup4;
    private readonly InputAction m_ControlGroups_ControlGroup5;
    private readonly InputAction m_ControlGroups_ControlGroup6;
    private readonly InputAction m_ControlGroups_ControlGroup7;
    private readonly InputAction m_ControlGroups_ControlGroup8;
    private readonly InputAction m_ControlGroups_ControlGroup9;
    public struct ControlGroupsActions
    {
        private @InputControls m_Wrapper;
        public ControlGroupsActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ControlGroup1 => m_Wrapper.m_ControlGroups_ControlGroup1;
        public InputAction @ControlGroup2 => m_Wrapper.m_ControlGroups_ControlGroup2;
        public InputAction @ControlGroup3 => m_Wrapper.m_ControlGroups_ControlGroup3;
        public InputAction @ControlGroup4 => m_Wrapper.m_ControlGroups_ControlGroup4;
        public InputAction @ControlGroup5 => m_Wrapper.m_ControlGroups_ControlGroup5;
        public InputAction @ControlGroup6 => m_Wrapper.m_ControlGroups_ControlGroup6;
        public InputAction @ControlGroup7 => m_Wrapper.m_ControlGroups_ControlGroup7;
        public InputAction @ControlGroup8 => m_Wrapper.m_ControlGroups_ControlGroup8;
        public InputAction @ControlGroup9 => m_Wrapper.m_ControlGroups_ControlGroup9;
        public InputActionMap Get() { return m_Wrapper.m_ControlGroups; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControlGroupsActions set) { return set.Get(); }
        public void AddCallbacks(IControlGroupsActions instance)
        {
            if (instance == null || m_Wrapper.m_ControlGroupsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControlGroupsActionsCallbackInterfaces.Add(instance);
            @ControlGroup1.started += instance.OnControlGroup1;
            @ControlGroup1.performed += instance.OnControlGroup1;
            @ControlGroup1.canceled += instance.OnControlGroup1;
            @ControlGroup2.started += instance.OnControlGroup2;
            @ControlGroup2.performed += instance.OnControlGroup2;
            @ControlGroup2.canceled += instance.OnControlGroup2;
            @ControlGroup3.started += instance.OnControlGroup3;
            @ControlGroup3.performed += instance.OnControlGroup3;
            @ControlGroup3.canceled += instance.OnControlGroup3;
            @ControlGroup4.started += instance.OnControlGroup4;
            @ControlGroup4.performed += instance.OnControlGroup4;
            @ControlGroup4.canceled += instance.OnControlGroup4;
            @ControlGroup5.started += instance.OnControlGroup5;
            @ControlGroup5.performed += instance.OnControlGroup5;
            @ControlGroup5.canceled += instance.OnControlGroup5;
            @ControlGroup6.started += instance.OnControlGroup6;
            @ControlGroup6.performed += instance.OnControlGroup6;
            @ControlGroup6.canceled += instance.OnControlGroup6;
            @ControlGroup7.started += instance.OnControlGroup7;
            @ControlGroup7.performed += instance.OnControlGroup7;
            @ControlGroup7.canceled += instance.OnControlGroup7;
            @ControlGroup8.started += instance.OnControlGroup8;
            @ControlGroup8.performed += instance.OnControlGroup8;
            @ControlGroup8.canceled += instance.OnControlGroup8;
            @ControlGroup9.started += instance.OnControlGroup9;
            @ControlGroup9.performed += instance.OnControlGroup9;
            @ControlGroup9.canceled += instance.OnControlGroup9;
        }

        private void UnregisterCallbacks(IControlGroupsActions instance)
        {
            @ControlGroup1.started -= instance.OnControlGroup1;
            @ControlGroup1.performed -= instance.OnControlGroup1;
            @ControlGroup1.canceled -= instance.OnControlGroup1;
            @ControlGroup2.started -= instance.OnControlGroup2;
            @ControlGroup2.performed -= instance.OnControlGroup2;
            @ControlGroup2.canceled -= instance.OnControlGroup2;
            @ControlGroup3.started -= instance.OnControlGroup3;
            @ControlGroup3.performed -= instance.OnControlGroup3;
            @ControlGroup3.canceled -= instance.OnControlGroup3;
            @ControlGroup4.started -= instance.OnControlGroup4;
            @ControlGroup4.performed -= instance.OnControlGroup4;
            @ControlGroup4.canceled -= instance.OnControlGroup4;
            @ControlGroup5.started -= instance.OnControlGroup5;
            @ControlGroup5.performed -= instance.OnControlGroup5;
            @ControlGroup5.canceled -= instance.OnControlGroup5;
            @ControlGroup6.started -= instance.OnControlGroup6;
            @ControlGroup6.performed -= instance.OnControlGroup6;
            @ControlGroup6.canceled -= instance.OnControlGroup6;
            @ControlGroup7.started -= instance.OnControlGroup7;
            @ControlGroup7.performed -= instance.OnControlGroup7;
            @ControlGroup7.canceled -= instance.OnControlGroup7;
            @ControlGroup8.started -= instance.OnControlGroup8;
            @ControlGroup8.performed -= instance.OnControlGroup8;
            @ControlGroup8.canceled -= instance.OnControlGroup8;
            @ControlGroup9.started -= instance.OnControlGroup9;
            @ControlGroup9.performed -= instance.OnControlGroup9;
            @ControlGroup9.canceled -= instance.OnControlGroup9;
        }

        public void RemoveCallbacks(IControlGroupsActions instance)
        {
            if (m_Wrapper.m_ControlGroupsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControlGroupsActions instance)
        {
            foreach (var item in m_Wrapper.m_ControlGroupsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControlGroupsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ControlGroupsActions @ControlGroups => new ControlGroupsActions(this);
    public interface IPlayerInputActions
    {
        void OnSelect(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnMouseDelta(InputAction.CallbackContext context);
        void OnLeftMousePress(InputAction.CallbackContext context);
        void OnLeftMouseRelease(InputAction.CallbackContext context);
        void OnRightMousePress(InputAction.CallbackContext context);
        void OnRightMouseRelease(InputAction.CallbackContext context);
        void OnScrollDelta(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnControl(InputAction.CallbackContext context);
    }
    public interface ICameraControlsActions
    {
        void OnCameraMovement(InputAction.CallbackContext context);
        void OnCameraSpeedModifier(InputAction.CallbackContext context);
        void OnCameraZoom(InputAction.CallbackContext context);
        void OnRotateCamera(InputAction.CallbackContext context);
        void OnPanCamera(InputAction.CallbackContext context);
        void OnFocusCamera(InputAction.CallbackContext context);
    }
    public interface ICommandsActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnStop(InputAction.CallbackContext context);
    }
    public interface IControlGroupsActions
    {
        void OnControlGroup1(InputAction.CallbackContext context);
        void OnControlGroup2(InputAction.CallbackContext context);
        void OnControlGroup3(InputAction.CallbackContext context);
        void OnControlGroup4(InputAction.CallbackContext context);
        void OnControlGroup5(InputAction.CallbackContext context);
        void OnControlGroup6(InputAction.CallbackContext context);
        void OnControlGroup7(InputAction.CallbackContext context);
        void OnControlGroup8(InputAction.CallbackContext context);
        void OnControlGroup9(InputAction.CallbackContext context);
    }
}
